INFO:werkzeug:127.0.0.1 - - [16/Oct/2024 18:49:44] "POST /opl/search-to-view-products HTTP/1.1" 200 -
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/gtrivedi/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "/home/gtrivedi/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 328, in execute
    write(data)
  File "/home/gtrivedi/.local/lib/python3.12/site-packages/werkzeug/serving.py", line 303, in write
    self.wfile.write(data)
  File "/usr/lib64/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
  File "/usr/lib64/python3.12/ssl.py", line 1210, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ssl.py", line 1179, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
