version: 1.1
features:
  - name: feature_1
    description: "Description of feature 1"
  - name: feature_2
    description: "Description of feature 2"
  - name: feature_3
    description: "Description of feature 3"
  - name: feature_4
    description: "Description of feature 4"

  - name: dance-all
    description: Dance Language Samples


Red Hat Trusted Application Pipeline (RHTAP) is not really a single product. Instead, it is a set of products that combine to form a highly automated, customizable, and secure platform for building applications.

RHTAP includes the following products:

Advanced Cluster Security (ACS): to scan your artifacts for vulnerabilities.
Developer Hub: a self-service portal for developers.
OpenShift GitOps: to manage Kubernetes deployments and their infrastructure.
OpenShift Pipelines: to enable automation and provide visibility for continuous integration and continuous delivery (CI/CD) of software.
Quay.io: a container registry, to store your artifacts.
Trusted Artifact Signer: to sign and validate the artifacts that RHTAP produces.
Trusted Profile Analyzer: to deliver actionable information about your security posture.
To see exactly which versions of these products RHTAP supports, reference the compatibility and support matrix in our Release notes.

Note
If you already have an instance of Quay.io or ACS, you can integrate it into your deployment of RHTAP.

Because a fully-operational instance of RHTAP involves all of the products listed above, installing RHTAP takes some effort. However, we have automated the vast majority of this process, and are providing instructions here that we hope are helpful and concise.

Additionally, be aware that the RHTAP installer is not a manager: it does not support upgrades. The installer generates your first deployment of RHTAP. After installation, you manage each product within RHTAP individually.

Before you can begin installation, you must meet six prerequisites. Then you must complete seven procedures.

Prerequisites

ClusterAdmin access to an OpenShift Container Platform (OCP) cluster, through both the CLI and the web console
The Helm CLI tool
A GitHub account
Procedures

Creating a GitOps token
Creating a GitHub application for RHTAP
Forking the template catalog
(Optional) Preparing to integrate your instance of Quay
(Optional) Preparing to integrate your instance of ACS
Customizing your config.yaml file
Deploying RHTAP in your cluster
The following pages of this document explain each of those procedures in detail. If you have the prerequisites, you are ready to start the installation process by creating a GitOps token.
