<!doctype html>
<html lang="en">
{% include 'head.html' %}

<body>
  <div class="pf-v5-c-page">
    {% include 'masthead.html' %}
    {% include 'menu.html' %}
    <main class="pf-v5-c-page__main" tabindex="-1">
      <section class="pf-v5-c-page__main-section pf-m-light">
        {% block heading %}{% endblock %}
      </section>
      <section class="pf-v5-c-page__main-section">
        {% block content %}{% endblock %}
      </section>
      {% block footer %}
      {% endblock %}
    </main>
  </div>
</body>

<script src="{{ url_for('static', filename='scripts/toggle.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/patternfly/4.160.0/patternfly.min.js"></script>

</html>
