version: 1.1
features:
  - name: feature_1
    description: "Description of feature 1"
  - name: feature_2
    description: "Description of feature 2"
  - name: feature_3
    description: "Description of feature 3"
  - name: feature_3a
    description: "Description of feature 3a"

  - name: dance-all
    description: Dance Language Samples
